import type { StoryWorldDefinition } from "./world.schema";
import { validateWorldDefinition } from "./world.schema";

const ACT_ONE_NODE_IDS = [
  "human",
  "intention",
  "msxai",
  "principle-intention-first",
  "principle-structure-story",
  "principle-repeatable-process",
  "principle-auditor-not-pilot",
  "principle-return-agency",
];

const ACT_ONE_RELATIONSHIP_IDS = [
  "human-holds-intention",
  "intention-to-msxai",
  "msxai-expresses-intention-first",
  "msxai-expresses-structure-story",
  "msxai-expresses-repeatable-process",
  "msxai-expresses-auditor-not-pilot",
  "msxai-expresses-return-agency",
];

const ECOSYSTEM_NODE_IDS = ["mindhome", "mss", "mhb", "wave-glass-project-h", "nutuensai", "lli"];
const ECOSYSTEM_RELATIONSHIP_IDS = [
  "msxai-concept-mindhome",
  "msxai-concept-mss",
  "msxai-concept-mhb",
  "msxai-concept-wave-glass-project-h",
  "msxai-concept-nutuensai",
  "msxai-concept-lli",
];

export const STORY_WORLD_V0_1: StoryWorldDefinition = {
  version: "0.1",
  title: "MSxAI 3D Story World",
  truthfulnessNotice:
    "An explorable conceptual world of the MSxAI ecosystem. This experience does not represent model reasoning, neural activity, or hidden AI cognition.",
  thaiTruthfulnessNotice:
    "โลกเชิงแนวคิดของระบบนิเวศ MSxAI ที่ผู้ใช้สามารถเข้าไปสำรวจได้ ประสบการณ์นี้ไม่ได้แสดงถึงกระบวนการให้เหตุผลของโมเดล การทำงานของโครงข่ายประสาท หรือกระบวนการรับรู้ภายในที่ซ่อนอยู่ของ AI",
  nodes: [
    {
      id: "human",
      label: "HUMAN",
      thaiLabel: "ผู้ถือเจตนา",
      kind: "human",
      position: [0, 1.15, 1.2],
      summary: "Intention Holder",
      thaiSummary: "ผู้ถือเจตนา",
      detail: ["The human holds the intention.", "This anchor is conceptual, not a profile or biometric model."],
      thaiDetail: ["มนุษย์เป็นผู้ถือเจตนา", "จุดยึดนี้เป็นแนวคิด ไม่ใช่โปรไฟล์หรือแบบจำลองชีวมิติ"],
    },
    {
      id: "intention",
      label: "INTENTION",
      thaiLabel: "เจตนาของมนุษย์",
      kind: "intention",
      position: [3, 2.7, -4.3],
      summary: "Human-held direction before execution.",
      thaiSummary: "ทิศทางที่มนุษย์ถือไว้ก่อนการปฏิบัติการ",
      detail: ["Intention is held by the human.", "It is not an AI prediction, hidden profile, or confidence score."],
      thaiDetail: ["เจตนาถูกถือไว้โดยมนุษย์", "ไม่ใช่การคาดการณ์ของ AI โปรไฟล์ที่ซ่อนอยู่ หรือค่าความเชื่อมั่น"],
    },
    {
      id: "msxai",
      label: "MSxAI",
      thaiLabel: "กรอบการทำงาน MSxAI",
      kind: "framework",
      position: [-0.8, 4.4, -12],
      summary: "Intention-First AI Alignment",
      thaiSummary: "การจัดแนว AI ที่เริ่มจากเจตนา",
      detail: [
        "Intention First",
        "Structure > Story",
        "Repeatable Process",
        "AI as Auditor, not Pilot",
        "Return the Agency",
      ],
      thaiDetail: [
        "เจตนามาก่อน",
        "โครงสร้างสำคัญกว่าเรื่องเล่า",
        "กระบวนการที่ทำซ้ำและตรวจสอบได้",
        "AI เป็นผู้ตรวจสอบ ไม่ใช่ผู้ขับเคลื่อนแทนมนุษย์",
        "คืนอำนาจการกำหนดและตัดสินใจให้มนุษย์",
      ],
    },
    {
      id: "principle-intention-first",
      label: "Intention First",
      thaiLabel: "เจตนามาก่อน",
      kind: "principle",
      position: [-5.3, 5.6, -12.7],
      summary: "Intention First",
      thaiSummary: "เจตนาของมนุษย์ต้องมาก่อน",
      detail: ["A declared MSxAI principle."],
      thaiDetail: ["หลักการ MSxAI ที่ประกาศไว้อย่างชัดเจน"],
    },
    {
      id: "principle-structure-story",
      label: "Structure > Story",
      thaiLabel: "โครงสร้างสำคัญกว่าเรื่องเล่า",
      kind: "principle",
      position: [3.4, 6.5, -14.5],
      summary: "Structure > Story",
      thaiSummary: "ให้ความสำคัญกับโครงสร้างมากกว่าเรื่องเล่า",
      detail: ["A declared MSxAI principle."],
      thaiDetail: ["หลักการ MSxAI ที่ประกาศไว้อย่างชัดเจน"],
    },
    {
      id: "principle-repeatable-process",
      label: "Repeatable Process",
      thaiLabel: "กระบวนการที่ทำซ้ำและตรวจสอบได้",
      kind: "principle",
      position: [5.2, 3.2, -15.8],
      summary: "Repeatable Process",
      thaiSummary: "กระบวนการที่ทำซ้ำและตรวจสอบได้",
      detail: ["A declared MSxAI principle."],
      thaiDetail: ["หลักการ MSxAI ที่ประกาศไว้อย่างชัดเจน"],
    },
    {
      id: "principle-auditor-not-pilot",
      label: "AI as Auditor, not Pilot",
      thaiLabel: "AI เป็นผู้ตรวจสอบ ไม่ใช่ผู้ขับเคลื่อนแทนมนุษย์",
      kind: "principle",
      position: [-3.8, 1.9, -15.4],
      summary: "AI as Auditor, not Pilot",
      thaiSummary: "AI ทำหน้าที่ตรวจสอบ โดยมนุษย์ยังเป็นผู้ขับเคลื่อน",
      detail: ["A declared MSxAI principle."],
      thaiDetail: ["หลักการ MSxAI ที่ประกาศไว้อย่างชัดเจน"],
    },
    {
      id: "principle-return-agency",
      label: "Return the Agency",
      thaiLabel: "คืนอำนาจการกำหนดและตัดสินใจให้มนุษย์",
      kind: "principle",
      position: [0.2, 7.8, -17.2],
      summary: "Return the Agency",
      thaiSummary: "คืนอำนาจการกำหนดและตัดสินใจให้มนุษย์",
      detail: ["A declared MSxAI principle."],
      thaiDetail: ["หลักการ MSxAI ที่ประกาศไว้อย่างชัดเจน"],
    },
    {
      id: "mindhome",
      label: "MindHome",
      thaiLabel: "MindHome",
      kind: "ecosystem-anchor",
      position: [-9.4, 8.5, -22.6],
      summary: "Human Agency & Alignment",
      thaiSummary: "พื้นที่สำหรับ Human Agency และ Alignment",
      detail: [
        "A space for understanding intention, uncertainty, and meaningful human agency.",
        "Part of the MSxAI ecosystem.",
      ],
      thaiDetail: [
        "พื้นที่สำหรับทำความเข้าใจเจตนา ความไม่แน่นอน และอำนาจการตัดสินใจที่มีความหมายของมนุษย์",
        "เป็นส่วนหนึ่งของระบบนิเวศ MSxAI",
      ],
    },
    {
      id: "mss",
      label: "MSS",
      thaiLabel: "MSS",
      kind: "ecosystem-anchor",
      position: [-11.3, 3.5, -21.5],
      summary: "Human–AI Workspace",
      thaiSummary: "พื้นที่ทำงานร่วมระหว่างมนุษย์กับ AI",
      detail: [
        "A workspace where people work with AI while keeping context visible and intentional.",
        "Part of the MSxAI ecosystem.",
      ],
      thaiDetail: [
        "พื้นที่ทำงานร่วมกับ AI ที่ช่วยให้บริบทและเจตนายังคงมองเห็นและกำหนดได้",
        "เป็นส่วนหนึ่งของระบบนิเวศ MSxAI",
      ],
    },
    {
      id: "mhb",
      label: "Mindful Health Balance",
      thaiLabel: "Mindful Health Balance (MHB)",
      kind: "ecosystem-anchor",
      position: [8.9, 4.2, -23.5],
      summary: "Everyday Self-Awareness",
      thaiSummary: "การตระหนักรู้ในชีวิตประจำวัน",
      detail: [
        "A personal space for observing everyday health, food, activity, and reflection in context.",
        "Part of the MSxAI ecosystem.",
      ],
      thaiDetail: [
        "พื้นที่ส่วนบุคคลสำหรับสังเกตสุขภาพ อาหาร กิจกรรม และการทบทวนตัวเองในบริบทของชีวิตประจำวัน",
        "เป็นส่วนหนึ่งของระบบนิเวศ MSxAI",
      ],
    },
    {
      id: "wave-glass-project-h",
      label: "Wave Glass / Project H",
      thaiLabel: "Wave Glass / Project H",
      kind: "ecosystem-anchor",
      position: [-6.2, 0.3, -26.8],
      summary: "Decision Clarity",
      thaiSummary: "ความชัดเจนก่อนการตัดสินใจ",
      detail: [
        "A space for observing information, structure, and state before making decisions.",
        "Part of the MSxAI ecosystem.",
      ],
      thaiDetail: [
        "พื้นที่สำหรับมองข้อมูล โครงสร้าง และสภาวะให้ชัดขึ้นก่อนตัดสินใจ",
        "เป็นส่วนหนึ่งของระบบนิเวศ MSxAI",
      ],
    },
    {
      id: "nutuensai",
      label: "NuTuenSai",
      thaiLabel: "NuTuenSai",
      kind: "listening-layer",
      position: [5.2, 0.7, -27.8],
      summary: "Listening & Interpretation Layer",
      thaiSummary: "ชั้นปฏิสัมพันธ์เพื่อการรับฟังและตีความเจตนา",
      detail: [
        "A reflective interaction layer that listens for intention across the ecosystem.",
        "Part of the MSxAI ecosystem.",
      ],
      thaiDetail: [
        "ชั้นปฏิสัมพันธ์เชิงสะท้อนที่รับฟังและช่วยรักษาเจตนาตลอดระบบนิเวศ",
        "เป็นส่วนหนึ่งของระบบนิเวศ MSxAI",
      ],
    },
    {
      id: "lli",
      label: "LLi",
      thaiLabel: "LLi",
      kind: "language-signal",
      position: [0.3, -0.1, -30.6],
      summary: "Intention Behind Language",
      thaiSummary: "เจตนาที่อยู่เบื้องหลังภาษา",
      detail: [
        "An idea for looking beyond words toward the intention carried through language.",
        "Part of the MSxAI ecosystem.",
      ],
      thaiDetail: [
        "แนวคิดที่มองลึกกว่าตัวคำ ไปยังเจตนาที่ถูกส่งผ่านภาษา",
        "เป็นส่วนหนึ่งของระบบนิเวศ MSxAI",
      ],
    },
  ],
  relationships: [
    {
      id: "human-holds-intention",
      from: "human",
      to: "intention",
      kind: "holds-intention",
      label: "Human holds Intention",
      thaiLabel: "มนุษย์เป็นผู้ถือเจตนา",
    },
    {
      id: "intention-to-msxai",
      from: "intention",
      to: "msxai",
      kind: "story-progression",
      label: "Intention enters the MSxAI framing",
      thaiLabel: "เจตนาเข้าสู่กรอบการทำงาน MSxAI",
    },
    {
      id: "msxai-expresses-intention-first",
      from: "msxai",
      to: "principle-intention-first",
      kind: "expresses-principle",
      label: "MSxAI expresses Intention First",
      thaiLabel: "MSxAI แสดงหลักการเจตนามาก่อน",
    },
    {
      id: "msxai-expresses-structure-story",
      from: "msxai",
      to: "principle-structure-story",
      kind: "expresses-principle",
      label: "MSxAI expresses Structure > Story",
      thaiLabel: "MSxAI แสดงหลักการโครงสร้างสำคัญกว่าเรื่องเล่า",
    },
    {
      id: "msxai-expresses-repeatable-process",
      from: "msxai",
      to: "principle-repeatable-process",
      kind: "expresses-principle",
      label: "MSxAI expresses Repeatable Process",
      thaiLabel: "MSxAI แสดงหลักการกระบวนการที่ทำซ้ำและตรวจสอบได้",
    },
    {
      id: "msxai-expresses-auditor-not-pilot",
      from: "msxai",
      to: "principle-auditor-not-pilot",
      kind: "expresses-principle",
      label: "MSxAI expresses AI as Auditor, not Pilot",
      thaiLabel: "MSxAI แสดงหลักการ AI เป็นผู้ตรวจสอบ ไม่ใช่ผู้ขับเคลื่อนแทนมนุษย์",
    },
    {
      id: "msxai-expresses-return-agency",
      from: "msxai",
      to: "principle-return-agency",
      kind: "expresses-principle",
      label: "MSxAI expresses Return the Agency",
      thaiLabel: "MSxAI แสดงหลักการคืนอำนาจการกำหนดและตัดสินใจให้มนุษย์",
    },
    {
      id: "msxai-concept-mindhome",
      from: "msxai",
      to: "mindhome",
      kind: "conceptual-connection",
      label: "MSxAI and MindHome share a direction of human agency.",
      thaiLabel: "MSxAI และ MindHome มีทิศทางร่วมกันในการรักษาอำนาจการตัดสินใจของมนุษย์",
    },
    {
      id: "msxai-concept-mss",
      from: "msxai",
      to: "mss",
      kind: "conceptual-connection",
      label: "MSxAI and MSS share an intentional human–AI workspace.",
      thaiLabel: "MSxAI และ MSS มีพื้นที่ทำงานร่วมระหว่างมนุษย์กับ AI ที่ยึดโยงกับเจตนา",
    },
    {
      id: "msxai-concept-mhb",
      from: "msxai",
      to: "mhb",
      kind: "conceptual-connection",
      label: "MSxAI and Mindful Health Balance share everyday reflection in context.",
      thaiLabel: "MSxAI และ Mindful Health Balance มีการทบทวนชีวิตประจำวันในบริบทเดียวกัน",
    },
    {
      id: "msxai-concept-wave-glass-project-h",
      from: "msxai",
      to: "wave-glass-project-h",
      kind: "conceptual-connection",
      label: "MSxAI and Wave Glass / Project H share a need for decision clarity.",
      thaiLabel: "MSxAI และ Wave Glass / Project H มีความมุ่งหมายร่วมกันเพื่อความชัดเจนก่อนการตัดสินใจ",
    },
    {
      id: "msxai-concept-nutuensai",
      from: "msxai",
      to: "nutuensai",
      kind: "conceptual-connection",
      label: "MSxAI and NuTuenSai share reflective attention to intention.",
      thaiLabel: "MSxAI และ NuTuenSai มีความใส่ใจเชิงสะท้อนต่อเจตนาร่วมกัน",
    },
    {
      id: "msxai-concept-lli",
      from: "msxai",
      to: "lli",
      kind: "conceptual-connection",
      label: "MSxAI and LLi share attention to intention carried through language.",
      thaiLabel: "MSxAI และ LLi ให้ความสำคัญร่วมกันต่อเจตนาที่ส่งผ่านภาษา",
    },
  ],
  cameraStates: [
    {
      id: "opening-camera",
      position: [7.2, 6.2, 20],
      target: [0.2, 1.2, -3.4],
      fov: 42,
      durationMs: 1000,
      allowManualControl: false,
    },
    {
      id: "human-camera",
      position: [5.7, 3.7, 10.5],
      target: [0, 1.25, 0.4],
      fov: 40,
      durationMs: 1050,
      allowManualControl: true,
    },
    {
      id: "intention-camera",
      position: [7.8, 5.1, 4.8],
      target: [1.7, 2.2, -3.8],
      fov: 46,
      durationMs: 1450,
      allowManualControl: true,
    },
    {
      id: "msxai-camera",
      position: [13.8, 9.7, 15.8],
      target: [-0.15, 3.6, -10.4],
      fov: 49,
      durationMs: 1650,
      allowManualControl: true,
    },
    {
      id: "ecosystem-overview-camera",
      position: [8.3, 8.4, 3.8],
      target: [-0.8, 3.4, -18.2],
      fov: 49,
      durationMs: 1450,
      allowManualControl: true,
    },
    {
      id: "mindhome-camera",
      position: [1, 9.4, -0.5],
      target: [-9.4, 8.5, -22.6],
      fov: 46,
      durationMs: 1300,
      allowManualControl: true,
    },
    {
      id: "mss-camera",
      position: [0.5, 4.7, -0.3],
      target: [-11.3, 3.5, -21.5],
      fov: 45,
      durationMs: 1300,
      allowManualControl: true,
    },
    {
      id: "mhb-camera",
      position: [3.6, 6.1, -0.7],
      target: [8.9, 4.2, -23.5],
      fov: 45,
      durationMs: 1300,
      allowManualControl: true,
    },
    {
      id: "wave-glass-camera",
      position: [1.4, 2.4, -4.5],
      target: [-6.2, 0.3, -26.8],
      fov: 46,
      durationMs: 1300,
      allowManualControl: true,
    },
    {
      id: "nutuensai-camera",
      position: [1.8, 3, -5],
      target: [5.2, 0.7, -27.8],
      fov: 46,
      durationMs: 1350,
      allowManualControl: true,
    },
    {
      id: "lli-camera",
      position: [1.4, 1.8, -7],
      target: [0.3, -0.1, -30.6],
      fov: 44,
      durationMs: 1200,
      allowManualControl: true,
    },
    {
      id: "return-agency-camera",
      position: [8, 7.2, 12.5],
      target: [0.3, 1.8, -11.8],
      fov: 52,
      durationMs: 1600,
      allowManualControl: true,
    },
  ],
  beats: [
    {
      id: "opening",
      order: 0,
      title: "MSxAI 3D Story World",
      thaiTitle: "โลกเรื่องเล่า 3 มิติของ MSxAI",
      lines: ["AI is becoming more capable.", "But who holds the intention?"],
      thaiLines: ["AI มีความสามารถมากขึ้น", "แล้วใครคือผู้ถือเจตนา?"],
      cameraStateId: "opening-camera",
      revealNodeIds: ["human"],
      revealRelationshipIds: [],
      nextLabel: "Begin the Story",
    },
    {
      id: "human",
      order: 1,
      title: "HUMAN",
      thaiTitle: "ผู้ถือเจตนา",
      lines: ["The human remains the intention holder."],
      thaiLines: ["มนุษย์ยังคงเป็นผู้ถือเจตนา"],
      cameraStateId: "human-camera",
      focusNodeId: "human",
      revealNodeIds: ["human"],
      revealRelationshipIds: [],
      nextLabel: "Reveal Intention",
    },
    {
      id: "intention",
      order: 2,
      title: "INTENTION",
      thaiTitle: "เจตนาของมนุษย์",
      lines: ["Human-held direction before execution."],
      thaiLines: ["ทิศทางที่มนุษย์ถือไว้ก่อนการปฏิบัติการ"],
      cameraStateId: "intention-camera",
      focusNodeId: "intention",
      revealNodeIds: ["human", "intention"],
      revealRelationshipIds: ["human-holds-intention"],
      nextLabel: "Reveal MSxAI",
    },
    {
      id: "msxai",
      order: 3,
      title: "MSxAI",
      thaiTitle: "กรอบการทำงาน MSxAI",
      lines: ["Intention-First AI Alignment"],
      thaiLines: ["การจัดแนว AI ที่เริ่มจากเจตนา"],
      cameraStateId: "msxai-camera",
      focusNodeId: "msxai",
      revealNodeIds: [
        "human",
        "intention",
        "msxai",
        "principle-intention-first",
        "principle-structure-story",
        "principle-repeatable-process",
        "principle-auditor-not-pilot",
        "principle-return-agency",
      ],
      revealRelationshipIds: [
        "human-holds-intention",
        "intention-to-msxai",
        "msxai-expresses-intention-first",
        "msxai-expresses-structure-story",
        "msxai-expresses-repeatable-process",
        "msxai-expresses-auditor-not-pilot",
        "msxai-expresses-return-agency",
      ],
    },
    {
      id: "living-ecosystem",
      order: 4,
      title: "THE LIVING ECOSYSTEM",
      thaiTitle: "ระบบนิเวศที่มีชีวิต",
      lines: ["MSxAI is not a single application.", "It is a growing ecosystem built around human intention."],
      thaiLines: ["MSxAI ไม่ใช่แอปพลิเคชันเพียงตัวเดียว", "แต่เป็นระบบนิเวศที่ค่อย ๆ เติบโตขึ้นรอบเจตนาของมนุษย์"],
      cameraStateId: "ecosystem-overview-camera",
      focusNodeId: "msxai",
      revealNodeIds: ACT_ONE_NODE_IDS,
      revealRelationshipIds: ACT_ONE_RELATIONSHIP_IDS,
    },
    {
      id: "mindhome",
      order: 5,
      title: "MindHome",
      thaiTitle: "MindHome",
      lines: ["A space for understanding intention, uncertainty, and meaningful human agency."],
      thaiLines: ["พื้นที่สำหรับทำความเข้าใจเจตนา ความไม่แน่นอน และอำนาจการตัดสินใจที่มีความหมายของมนุษย์"],
      cameraStateId: "mindhome-camera",
      focusNodeId: "mindhome",
      revealNodeIds: [...ACT_ONE_NODE_IDS, "mindhome"],
      revealRelationshipIds: [...ACT_ONE_RELATIONSHIP_IDS, "msxai-concept-mindhome"],
    },
    {
      id: "mss",
      order: 6,
      title: "MSS",
      thaiTitle: "MSS",
      lines: ["A workspace where people work with AI while keeping context visible and intentional."],
      thaiLines: ["พื้นที่ทำงานร่วมกับ AI ที่ช่วยให้บริบทและเจตนายังคงมองเห็นและกำหนดได้"],
      cameraStateId: "mss-camera",
      focusNodeId: "mss",
      revealNodeIds: [...ACT_ONE_NODE_IDS, "mindhome", "mss"],
      revealRelationshipIds: [...ACT_ONE_RELATIONSHIP_IDS, "msxai-concept-mindhome", "msxai-concept-mss"],
    },
    {
      id: "mhb",
      order: 7,
      title: "Mindful Health Balance",
      thaiTitle: "Mindful Health Balance (MHB)",
      lines: ["A personal space for observing everyday health, food, activity, and reflection in context."],
      thaiLines: ["พื้นที่ส่วนบุคคลสำหรับสังเกตสุขภาพ อาหาร กิจกรรม และการทบทวนตัวเองในบริบทของชีวิตประจำวัน"],
      cameraStateId: "mhb-camera",
      focusNodeId: "mhb",
      revealNodeIds: [...ACT_ONE_NODE_IDS, "mindhome", "mss", "mhb"],
      revealRelationshipIds: [...ACT_ONE_RELATIONSHIP_IDS, "msxai-concept-mindhome", "msxai-concept-mss", "msxai-concept-mhb"],
    },
    {
      id: "wave-glass-project-h",
      order: 8,
      title: "Wave Glass / Project H",
      thaiTitle: "Wave Glass / Project H",
      lines: ["A space for observing information, structure, and state before making decisions."],
      thaiLines: ["พื้นที่สำหรับมองข้อมูล โครงสร้าง และสภาวะให้ชัดขึ้นก่อนตัดสินใจ"],
      cameraStateId: "wave-glass-camera",
      focusNodeId: "wave-glass-project-h",
      revealNodeIds: [...ACT_ONE_NODE_IDS, "mindhome", "mss", "mhb", "wave-glass-project-h"],
      revealRelationshipIds: [
        ...ACT_ONE_RELATIONSHIP_IDS,
        "msxai-concept-mindhome",
        "msxai-concept-mss",
        "msxai-concept-mhb",
        "msxai-concept-wave-glass-project-h",
      ],
    },
    {
      id: "nutuensai",
      order: 9,
      title: "NuTuenSai",
      thaiTitle: "NuTuenSai",
      lines: ["A reflective interaction layer that listens for intention across the ecosystem."],
      thaiLines: ["ชั้นปฏิสัมพันธ์เชิงสะท้อนที่รับฟังและช่วยรักษาเจตนาตลอดระบบนิเวศ"],
      cameraStateId: "nutuensai-camera",
      focusNodeId: "nutuensai",
      revealNodeIds: [...ACT_ONE_NODE_IDS, "mindhome", "mss", "mhb", "wave-glass-project-h", "nutuensai"],
      revealRelationshipIds: [
        ...ACT_ONE_RELATIONSHIP_IDS,
        "msxai-concept-mindhome",
        "msxai-concept-mss",
        "msxai-concept-mhb",
        "msxai-concept-wave-glass-project-h",
        "msxai-concept-nutuensai",
      ],
    },
    {
      id: "lli",
      order: 10,
      title: "LLi",
      thaiTitle: "LLi",
      lines: ["An idea for looking beyond words toward the intention carried through language."],
      thaiLines: ["แนวคิดที่มองลึกกว่าตัวคำ ไปยังเจตนาที่ถูกส่งผ่านภาษา"],
      cameraStateId: "lli-camera",
      focusNodeId: "lli",
      revealNodeIds: [...ACT_ONE_NODE_IDS, ...ECOSYSTEM_NODE_IDS],
      revealRelationshipIds: [...ACT_ONE_RELATIONSHIP_IDS, ...ECOSYSTEM_RELATIONSHIP_IDS],
    },
    {
      id: "return-agency",
      order: 11,
      title: "Return the Agency",
      thaiTitle: "คืนอำนาจการกำหนดและตัดสินใจให้มนุษย์",
      lines: [
        "Different systems. Different purposes.",
        "One shared direction.",
        "Keep the human able to observe, understand, and decide.",
        "Return the Agency.",
      ],
      thaiLines: [
        "ต่างระบบ ต่างหน้าที่",
        "แต่มีทิศทางร่วมกัน",
        "ให้มนุษย์ยังสามารถสังเกต ทำความเข้าใจ และตัดสินใจได้ด้วยตนเอง",
        "คืนอำนาจการกำหนดและตัดสินใจให้มนุษย์",
      ],
      cameraStateId: "return-agency-camera",
      focusNodeId: "human",
      revealNodeIds: [...ACT_ONE_NODE_IDS, ...ECOSYSTEM_NODE_IDS],
      revealRelationshipIds: [...ACT_ONE_RELATIONSHIP_IDS, ...ECOSYSTEM_RELATIONSHIP_IDS],
    },
  ],
};

validateWorldDefinition(STORY_WORLD_V0_1);
