import type { StoryWorldDefinition } from "./world.schema";
import { validateWorldDefinition } from "./world.schema";

export const STORY_WORLD_V0_1: StoryWorldDefinition = {
  version: "0.1",
  title: "MSxAI 3D Story World",
  truthfulnessNotice:
    "An explorable conceptual world of the MSxAI ecosystem. This experience does not represent model reasoning, neural activity, or hidden AI cognition.",
  thaiTruthfulnessNotice:
    "โลกเชิงแนวคิดของระบบนิเวศ MSxAI ที่ผู้ใช้สามารถเข้าไปสำรวจได้ ประสบการณ์นี้ไม่ได้แสดงถึงกระบวนการให้เหตุผลของโมเดล การทำงานของโครงข่ายประสาท หรือกระบวนการรับรู้ภายในที่ซ่อนอยู่ของ AI",
  nodes: [
    {
      id: "human",
      label: "HUMAN",
      thaiLabel: "ผู้ถือเจตนา",
      kind: "human",
      position: [0, 1.15, 1.2],
      summary: "Intention Holder",
      thaiSummary: "ผู้ถือเจตนา",
      detail: ["The human holds the intention.", "This anchor is conceptual, not a profile or biometric model."],
      thaiDetail: ["มนุษย์เป็นผู้ถือเจตนา", "จุดยึดนี้เป็นแนวคิด ไม่ใช่โปรไฟล์หรือแบบจำลองชีวมิติ"],
    },
    {
      id: "intention",
      label: "INTENTION",
      thaiLabel: "เจตนาของมนุษย์",
      kind: "intention",
      position: [3, 2.7, -4.3],
      summary: "Human-held direction before execution.",
      thaiSummary: "ทิศทางที่มนุษย์ถือไว้ก่อนการปฏิบัติการ",
      detail: ["Intention is held by the human.", "It is not an AI prediction, hidden profile, or confidence score."],
      thaiDetail: ["เจตนาถูกถือไว้โดยมนุษย์", "ไม่ใช่การคาดการณ์ของ AI โปรไฟล์ที่ซ่อนอยู่ หรือค่าความเชื่อมั่น"],
    },
    {
      id: "msxai",
      label: "MSxAI",
      thaiLabel: "กรอบการทำงาน MSxAI",
      kind: "framework",
      position: [-0.8, 4.4, -12],
      summary: "Intention-First AI Alignment",
      thaiSummary: "การจัดแนว AI ที่เริ่มจากเจตนา",
      detail: [
        "Intention First",
        "Structure > Story",
        "Repeatable Process",
        "AI as Auditor, not Pilot",
        "Return the Agency",
      ],
      thaiDetail: [
        "เจตนามาก่อน",
        "โครงสร้างสำคัญกว่าเรื่องเล่า",
        "กระบวนการที่ทำซ้ำและตรวจสอบได้",
        "AI เป็นผู้ตรวจสอบ ไม่ใช่ผู้ขับเคลื่อนแทนมนุษย์",
        "คืนอำนาจการกำหนดและตัดสินใจให้มนุษย์",
      ],
    },
    {
      id: "principle-intention-first",
      label: "Intention First",
      thaiLabel: "เจตนามาก่อน",
      kind: "principle",
      position: [-5.3, 5.6, -12.7],
      summary: "Intention First",
      thaiSummary: "เจตนาของมนุษย์ต้องมาก่อน",
      detail: ["A declared MSxAI principle."],
      thaiDetail: ["หลักการ MSxAI ที่ประกาศไว้อย่างชัดเจน"],
    },
    {
      id: "principle-structure-story",
      label: "Structure > Story",
      thaiLabel: "โครงสร้างสำคัญกว่าเรื่องเล่า",
      kind: "principle",
      position: [3.4, 6.5, -14.5],
      summary: "Structure > Story",
      thaiSummary: "ให้ความสำคัญกับโครงสร้างมากกว่าเรื่องเล่า",
      detail: ["A declared MSxAI principle."],
      thaiDetail: ["หลักการ MSxAI ที่ประกาศไว้อย่างชัดเจน"],
    },
    {
      id: "principle-repeatable-process",
      label: "Repeatable Process",
      thaiLabel: "กระบวนการที่ทำซ้ำและตรวจสอบได้",
      kind: "principle",
      position: [5.2, 3.2, -15.8],
      summary: "Repeatable Process",
      thaiSummary: "กระบวนการที่ทำซ้ำและตรวจสอบได้",
      detail: ["A declared MSxAI principle."],
      thaiDetail: ["หลักการ MSxAI ที่ประกาศไว้อย่างชัดเจน"],
    },
    {
      id: "principle-auditor-not-pilot",
      label: "AI as Auditor, not Pilot",
      thaiLabel: "AI เป็นผู้ตรวจสอบ ไม่ใช่ผู้ขับเคลื่อนแทนมนุษย์",
      kind: "principle",
      position: [-3.8, 1.9, -15.4],
      summary: "AI as Auditor, not Pilot",
      thaiSummary: "AI ทำหน้าที่ตรวจสอบ โดยมนุษย์ยังเป็นผู้ขับเคลื่อน",
      detail: ["A declared MSxAI principle."],
      thaiDetail: ["หลักการ MSxAI ที่ประกาศไว้อย่างชัดเจน"],
    },
    {
      id: "principle-return-agency",
      label: "Return the Agency",
      thaiLabel: "คืนอำนาจการกำหนดและตัดสินใจให้มนุษย์",
      kind: "principle",
      position: [0.2, 7.8, -17.2],
      summary: "Return the Agency",
      thaiSummary: "คืนอำนาจการกำหนดและตัดสินใจให้มนุษย์",
      detail: ["A declared MSxAI principle."],
      thaiDetail: ["หลักการ MSxAI ที่ประกาศไว้อย่างชัดเจน"],
    },
  ],
  relationships: [
    {
      id: "human-holds-intention",
      from: "human",
      to: "intention",
      kind: "holds-intention",
      label: "Human holds Intention",
      thaiLabel: "มนุษย์เป็นผู้ถือเจตนา",
    },
    {
      id: "intention-to-msxai",
      from: "intention",
      to: "msxai",
      kind: "story-progression",
      label: "Intention enters the MSxAI framing",
      thaiLabel: "เจตนาเข้าสู่กรอบการทำงาน MSxAI",
    },
    {
      id: "msxai-expresses-intention-first",
      from: "msxai",
      to: "principle-intention-first",
      kind: "expresses-principle",
      label: "MSxAI expresses Intention First",
      thaiLabel: "MSxAI แสดงหลักการเจตนามาก่อน",
    },
    {
      id: "msxai-expresses-structure-story",
      from: "msxai",
      to: "principle-structure-story",
      kind: "expresses-principle",
      label: "MSxAI expresses Structure > Story",
      thaiLabel: "MSxAI แสดงหลักการโครงสร้างสำคัญกว่าเรื่องเล่า",
    },
    {
      id: "msxai-expresses-repeatable-process",
      from: "msxai",
      to: "principle-repeatable-process",
      kind: "expresses-principle",
      label: "MSxAI expresses Repeatable Process",
      thaiLabel: "MSxAI แสดงหลักการกระบวนการที่ทำซ้ำและตรวจสอบได้",
    },
    {
      id: "msxai-expresses-auditor-not-pilot",
      from: "msxai",
      to: "principle-auditor-not-pilot",
      kind: "expresses-principle",
      label: "MSxAI expresses AI as Auditor, not Pilot",
      thaiLabel: "MSxAI แสดงหลักการ AI เป็นผู้ตรวจสอบ ไม่ใช่ผู้ขับเคลื่อนแทนมนุษย์",
    },
    {
      id: "msxai-expresses-return-agency",
      from: "msxai",
      to: "principle-return-agency",
      kind: "expresses-principle",
      label: "MSxAI expresses Return the Agency",
      thaiLabel: "MSxAI แสดงหลักการคืนอำนาจการกำหนดและตัดสินใจให้มนุษย์",
    },
  ],
  cameraStates: [
    {
      id: "opening-camera",
      position: [7.2, 6.2, 20],
      target: [0.2, 1.2, -3.4],
      fov: 42,
      durationMs: 1000,
      allowManualControl: false,
    },
    {
      id: "human-camera",
      position: [5.7, 3.7, 10.5],
      target: [0, 1.25, 0.4],
      fov: 40,
      durationMs: 1050,
      allowManualControl: true,
    },
    {
      id: "intention-camera",
      position: [7.8, 5.1, 4.8],
      target: [1.7, 2.2, -3.8],
      fov: 46,
      durationMs: 1450,
      allowManualControl: true,
    },
    {
      id: "msxai-camera",
      position: [13.8, 9.7, 15.8],
      target: [-0.15, 3.6, -10.4],
      fov: 49,
      durationMs: 1650,
      allowManualControl: true,
    },
  ],
  beats: [
    {
      id: "opening",
      order: 0,
      title: "MSxAI 3D Story World",
      thaiTitle: "โลกเรื่องเล่า 3 มิติของ MSxAI",
      lines: ["AI is becoming more capable.", "But who holds the intention?"],
      thaiLines: ["AI มีความสามารถมากขึ้น", "แล้วใครคือผู้ถือเจตนา?"],
      cameraStateId: "opening-camera",
      revealNodeIds: ["human"],
      revealRelationshipIds: [],
      nextLabel: "Begin the Story",
    },
    {
      id: "human",
      order: 1,
      title: "HUMAN",
      thaiTitle: "ผู้ถือเจตนา",
      lines: ["The human remains the intention holder."],
      thaiLines: ["มนุษย์ยังคงเป็นผู้ถือเจตนา"],
      cameraStateId: "human-camera",
      focusNodeId: "human",
      revealNodeIds: ["human"],
      revealRelationshipIds: [],
      nextLabel: "Reveal Intention",
    },
    {
      id: "intention",
      order: 2,
      title: "INTENTION",
      thaiTitle: "เจตนาของมนุษย์",
      lines: ["Human-held direction before execution."],
      thaiLines: ["ทิศทางที่มนุษย์ถือไว้ก่อนการปฏิบัติการ"],
      cameraStateId: "intention-camera",
      focusNodeId: "intention",
      revealNodeIds: ["human", "intention"],
      revealRelationshipIds: ["human-holds-intention"],
      nextLabel: "Reveal MSxAI",
    },
    {
      id: "msxai",
      order: 3,
      title: "MSxAI",
      thaiTitle: "กรอบการทำงาน MSxAI",
      lines: ["Intention-First AI Alignment"],
      thaiLines: ["การจัดแนว AI ที่เริ่มจากเจตนา"],
      cameraStateId: "msxai-camera",
      focusNodeId: "msxai",
      revealNodeIds: [
        "human",
        "intention",
        "msxai",
        "principle-intention-first",
        "principle-structure-story",
        "principle-repeatable-process",
        "principle-auditor-not-pilot",
        "principle-return-agency",
      ],
      revealRelationshipIds: [
        "human-holds-intention",
        "intention-to-msxai",
        "msxai-expresses-intention-first",
        "msxai-expresses-structure-story",
        "msxai-expresses-repeatable-process",
        "msxai-expresses-auditor-not-pilot",
        "msxai-expresses-return-agency",
      ],
    },
  ],
};

validateWorldDefinition(STORY_WORLD_V0_1);
